version: "3.9"

services:
  db-real-estate:
     image: postgres:16.1
     restart: always
     ports:
        - "5432:5432"
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=real_estate
